[tool.ruff]
line-length = 120
select = ["E", "W", "F", "C90", "E", "W", "F", "C90", "D"]

exclude = [
    "**/__init__.py"
]

ignore = [
    "D107", "D410", "D411", "D412", "D413", "D401", "E402", "C901"
]

[tool.black]
line-length = 120

[tool.pylint]
max-line-length = 120
disable = ["C0103", "E0401", "R1710"]
